### ISSUE TITLE
[ubuntu] No candidate version available for docker-engine

### ISSUE THREAD

**Issue by scalp42** [chef-cookbooks/docker#644]
Not sure if it's related to a new change or missing an `apt-get update` somewhere, but I noticed our AMI builds are not passing anymore using `0.10.1` as version (and `2.4.24` cookbook version):

```
    ubuntu-14.04-chef-hvm-ebs_data: [2016-02-12T22:30:22+00:00] INFO: Processing docker_service[default] action create (gz-docker::default line 38)
    ubuntu-14.04-chef-hvm-ebs_data: [2016-02-12T22:30:22+00:00] INFO: Processing docker_installation_package[default] action create (/var/chef/cache/cookbooks/docker/libraries/docker_service.rb line 61)
    ubuntu-14.04-chef-hvm-ebs_data: [2016-02-12T22:30:22+00:00] INFO: Processing apt_package[docker-engine] action install (/var/chef/cache/cookbooks/docker/libraries/docker_installation_package.rb line 16)
    ubuntu-14.04-chef-hvm-ebs_data:
    ubuntu-14.04-chef-hvm-ebs_data: ================================================================================
    ubuntu-14.04-chef-hvm-ebs_data: Error executing action `install` on resource 'apt_package[docker-engine]'
    ubuntu-14.04-chef-hvm-ebs_data: ================================================================================
    ubuntu-14.04-chef-hvm-ebs_data:
    ubuntu-14.04-chef-hvm-ebs_data: Chef::Exceptions::Package
    ubuntu-14.04-chef-hvm-ebs_data: -------------------------
    ubuntu-14.04-chef-hvm-ebs_data: No candidate version available for docker-engine
    ubuntu-14.04-chef-hvm-ebs_data:
    ubuntu-14.04-chef-hvm-ebs_data: Cookbook Trace:
    ubuntu-14.04-chef-hvm-ebs_data: ---------------
    ubuntu-14.04-chef-hvm-ebs_data: /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:119:in `compile_and_converge_action'
    ubuntu-14.04-chef-hvm-ebs_data: /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:119:in `compile_and_converge_action'
    ubuntu-14.04-chef-hvm-ebs_data:
    ubuntu-14.04-chef-hvm-ebs_data: Resource Declaration:
    ubuntu-14.04-chef-hvm-ebs_data: ---------------------
    ubuntu-14.04-chef-hvm-ebs_data: # In /var/chef/cache/cookbooks/docker/libraries/docker_installation_package.rb
    ubuntu-14.04-chef-hvm-ebs_data:
    ubuntu-14.04-chef-hvm-ebs_data: 16:       package package_name do
    ubuntu-14.04-chef-hvm-ebs_data: 17:         version package_version
    ubuntu-14.04-chef-hvm-ebs_data: 18:         action :install
    ubuntu-14.04-chef-hvm-ebs_data: 19:       end
    ubuntu-14.04-chef-hvm-ebs_data: 20:     end
    ubuntu-14.04-chef-hvm-ebs_data:
    ubuntu-14.04-chef-hvm-ebs_data: Compiled Resource:
    ubuntu-14.04-chef-hvm-ebs_data: ------------------
    ubuntu-14.04-chef-hvm-ebs_data: # Declared in /var/chef/cache/cookbooks/docker/libraries/docker_installation_package.rb:16:in `block in <class:DockerInstallationPackage>'
    ubuntu-14.04-chef-hvm-ebs_data:
    ubuntu-14.04-chef-hvm-ebs_data: apt_package("docker-engine") do
    ubuntu-14.04-chef-hvm-ebs_data: package_name "docker-engine"
    ubuntu-14.04-chef-hvm-ebs_data: action [:install]
    ubuntu-14.04-chef-hvm-ebs_data: retries 0
    ubuntu-14.04-chef-hvm-ebs_data: retry_delay 2
    ubuntu-14.04-chef-hvm-ebs_data: default_guard_interpreter :default
    ubuntu-14.04-chef-hvm-ebs_data: declared_type :package
    ubuntu-14.04-chef-hvm-ebs_data: cookbook_name "gz-docker"
    ubuntu-14.04-chef-hvm-ebs_data: version "1.10.1-0~trusty"
    ubuntu-14.04-chef-hvm-ebs_data: end
    ubuntu-14.04-chef-hvm-ebs_data:
    ubuntu-14.04-chef-hvm-ebs_data: [2016-02-12T22:30:24+00:00] INFO: Running queued delayed notifications before re-raising exception
    ubuntu-14.04-chef-hvm-ebs_data:
    ubuntu-14.04-chef-hvm-ebs_data: ================================================================================
    ubuntu-14.04-chef-hvm-ebs_data: Error executing action `create` on resource 'docker_installation_package[default]'
    ubuntu-14.04-chef-hvm-ebs_data: ================================================================================
    ubuntu-14.04-chef-hvm-ebs_data:
    ubuntu-14.04-chef-hvm-ebs_data: Chef::Exceptions::Package
    ubuntu-14.04-chef-hvm-ebs_data: -------------------------
    ubuntu-14.04-chef-hvm-ebs_data: apt_package[docker-engine] (/var/chef/cache/cookbooks/docker/libraries/docker_installation_package.rb line 16) had an error: Chef::Exceptions::Package: No candidate version available for docker-engine
    ubuntu-14.04-chef-hvm-ebs_data:
    ubuntu-14.04-chef-hvm-ebs_data: Cookbook Trace:
    ubuntu-14.04-chef-hvm-ebs_data: ---------------
    ubuntu-14.04-chef-hvm-ebs_data: /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:119:in `compile_and_converge_action'
    ubuntu-14.04-chef-hvm-ebs_data: /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:119:in `compile_and_converge_action'
    ubuntu-14.04-chef-hvm-ebs_data:
    ubuntu-14.04-chef-hvm-ebs_data: Resource Declaration:
    ubuntu-14.04-chef-hvm-ebs_data: ---------------------
    ubuntu-14.04-chef-hvm-ebs_data: # In /var/chef/cache/cookbooks/docker/libraries/docker_service.rb
    ubuntu-14.04-chef-hvm-ebs_data:
    ubuntu-14.04-chef-hvm-ebs_data: 61:           install = docker_installation_package(name, &block)
    ubuntu-14.04-chef-hvm-ebs_data: 62:         when 'none'
    ubuntu-14.04-chef-hvm-ebs_data: 63:           Chef::Log.info('Skipping Docker installation. Assuming it was handled previously.')
    ubuntu-14.04-chef-hvm-ebs_data: 64:           return
    ubuntu-14.04-chef-hvm-ebs_data: 65:         end
    ubuntu-14.04-chef-hvm-ebs_data: 66:         copy_properties_to(install)
    ubuntu-14.04-chef-hvm-ebs_data:
    ubuntu-14.04-chef-hvm-ebs_data: Compiled Resource:
    ubuntu-14.04-chef-hvm-ebs_data: ------------------
    ubuntu-14.04-chef-hvm-ebs_data: # Declared in /var/chef/cache/cookbooks/docker/libraries/docker_service.rb:61:in `installation'
    ubuntu-14.04-chef-hvm-ebs_data:
    ubuntu-14.04-chef-hvm-ebs_data: docker_installation_package("default") do
    ubuntu-14.04-chef-hvm-ebs_data: action [:create]
    ubuntu-14.04-chef-hvm-ebs_data: retries 0
    ubuntu-14.04-chef-hvm-ebs_data: retry_delay 2
    ubuntu-14.04-chef-hvm-ebs_data: default_guard_interpreter :default
    ubuntu-14.04-chef-hvm-ebs_data: declared_type :docker_installation_package
    ubuntu-14.04-chef-hvm-ebs_data: cookbook_name "gz-docker"
    ubuntu-14.04-chef-hvm-ebs_data: version "1.10.1"
    ubuntu-14.04-chef-hvm-ebs_data: package_name "docker-engine"
    ubuntu-14.04-chef-hvm-ebs_data: package_version "1.10.1-0~trusty"
    ubuntu-14.04-chef-hvm-ebs_data: end
    ubuntu-14.04-chef-hvm-ebs_data:
    ubuntu-14.04-chef-hvm-ebs_data: [2016-02-12T22:30:24+00:00] INFO: Running queued delayed notifications before re-raising exception
    ubuntu-14.04-chef-hvm-ebs_data:
    ubuntu-14.04-chef-hvm-ebs_data: ================================================================================
    ubuntu-14.04-chef-hvm-ebs_data: Error executing action `create` on resource 'docker_service[default]'
    ubuntu-14.04-chef-hvm-ebs_data: ================================================================================
    ubuntu-14.04-chef-hvm-ebs_data:
    ubuntu-14.04-chef-hvm-ebs_data: Chef::Exceptions::Package
    ubuntu-14.04-chef-hvm-ebs_data: -------------------------
    ubuntu-14.04-chef-hvm-ebs_data: docker_installation_package[default] (/var/chef/cache/cookbooks/docker/libraries/docker_service.rb line 61) had an error: Chef::Exceptions::Package: apt_package[docker-engine] (/var/chef/cache/cookbooks/docker/libraries/docker_installation_package.rb line 16) had an error: Chef::Exceptions::Package: No candidate version available for docker-engine
    ubuntu-14.04-chef-hvm-ebs_data:
    ubuntu-14.04-chef-hvm-ebs_data: Cookbook Trace:
    ubuntu-14.04-chef-hvm-ebs_data: ---------------
    ubuntu-14.04-chef-hvm-ebs_data: /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:119:in `compile_and_converge_action'
    ubuntu-14.04-chef-hvm-ebs_data: /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:119:in `compile_and_converge_action'
    ubuntu-14.04-chef-hvm-ebs_data:
    ubuntu-14.04-chef-hvm-ebs_data: Resource Declaration:
    ubuntu-14.04-chef-hvm-ebs_data: ---------------------
    ubuntu-14.04-chef-hvm-ebs_data: # In /var/chef/cache/cookbooks/gz-docker/recipes/default.rb
    ubuntu-14.04-chef-hvm-ebs_data:
    ubuntu-14.04-chef-hvm-ebs_data: 38: docker_service 'default' do
    ubuntu-14.04-chef-hvm-ebs_data: 39:   dns node['gz-docker']['config']['dns']
    ubuntu-14.04-chef-hvm-ebs_data: 40:   graph node['gz-docker']['config']['graph']
    ubuntu-14.04-chef-hvm-ebs_data: 41:   log_driver node['gz-docker']['config']['log_driver']
    ubuntu-14.04-chef-hvm-ebs_data: 42:   log_opts ['max-file=10', 'max-size=5m']
    ubuntu-14.04-chef-hvm-ebs_data: 43:   storage_driver node['gz-docker']['config']['storage_driver']
    ubuntu-14.04-chef-hvm-ebs_data: 44:   version node['gz-docker']['config']['version']
    ubuntu-14.04-chef-hvm-ebs_data: 45:   install_method node['gz-docker']['config']['install_method']
    ubuntu-14.04-chef-hvm-ebs_data: 46:   action service_status
    ubuntu-14.04-chef-hvm-ebs_data: 47: end
    ubuntu-14.04-chef-hvm-ebs_data: 48:
    ubuntu-14.04-chef-hvm-ebs_data:
    ubuntu-14.04-chef-hvm-ebs_data: Compiled Resource:
    ubuntu-14.04-chef-hvm-ebs_data: ------------------
    ubuntu-14.04-chef-hvm-ebs_data: # Declared in /var/chef/cache/cookbooks/gz-docker/recipes/default.rb:38:in `from_file'
    ubuntu-14.04-chef-hvm-ebs_data:
    ubuntu-14.04-chef-hvm-ebs_data: docker_service("default") do
    ubuntu-14.04-chef-hvm-ebs_data: action [:create, :start]
    ubuntu-14.04-chef-hvm-ebs_data: retries 0
    ubuntu-14.04-chef-hvm-ebs_data: retry_delay 2
    ubuntu-14.04-chef-hvm-ebs_data: default_guard_interpreter :default
    ubuntu-14.04-chef-hvm-ebs_data: declared_type :docker_service
    ubuntu-14.04-chef-hvm-ebs_data: cookbook_name "gz-docker"
    ubuntu-14.04-chef-hvm-ebs_data: recipe_name "default"
    ubuntu-14.04-chef-hvm-ebs_data: dns ["8.8.8.8"]
    ubuntu-14.04-chef-hvm-ebs_data: graph "/docker"
    ubuntu-14.04-chef-hvm-ebs_data: log_driver "json-file"
    ubuntu-14.04-chef-hvm-ebs_data: log_opts ["max-file=10", "max-size=5m"]
    ubuntu-14.04-chef-hvm-ebs_data: storage_driver ["overlay"]
    ubuntu-14.04-chef-hvm-ebs_data: version "1.10.1"
    ubuntu-14.04-chef-hvm-ebs_data: install_method "package"
    ubuntu-14.04-chef-hvm-ebs_data: end
    ubuntu-14.04-chef-hvm-ebs_data:
```

Will poke around.
