### ISSUE TITLE
Does not install on Ubuntu packages >= 1.12.4

### ISSUE THREAD

**Issue by ryantm** [chef-cookbooks/docker#782]
### Cookbook version
2.13.0

### Chef-client version
Chef 12.5.1

### Platform Details

Linode VPS

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

### Scenario:
Install docker

### Steps to Reproduce:

Make a cookbook that depends on the docker cookbook and use this recipe:
```ruby
docker_service 'default' do
  action [:create, :start]
end
```

### Expected Result:
Docker is installed

### Actual Result:
Chef hangs forever and does not install docker. Probably due to https://github.com/docker/docker/issues/23347

### Workaround

Use the 'overlay' storage driver by default.
```ruby
docker_service 'default' do
  storage_driver 'overlay'
  action [:create, :start]
end
```

**Comment by nozpheratu** [comment]
Works for me:
```yaml
---
driver:
  name: vagrant
  require_chef_omnibus: 12.5.1
  vagrantfiles:
    - .kitchen.vagrant_cachier.rb

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu/xenial64

suites:
  - name: default
    run_list:
      - recipe[my_docker_wrapper::default]
    attributes:
```

I'm using it in production as well.
