### ISSUE TITLE
undefined method `property_is_set?'

### ISSUE THREAD

**Issue by anidesh1512** [chef-cookbooks/docker#989]
### Cookbook version
4.1.1

### Chef-client version
14.0.190

### Platform Details
Vagrant bento/centos-7.3

### Scenario:
Trying to use docker_service resource and get the above error in Test Kitchen. Test Kitchen version is  1.17.0

### Steps to Reproduce:
Test Kitchen yml is something like as follows:

```
---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  client_rb:
    environment: kitchen

verifier:
  name: inspec

platforms:
  - name: test
    driver:
      box: bento/centos-7.3
      network:
        - ["private_network", { type: "dhcp" }]
      provider: virtualbox
      ssh:
        keep_alive: true
```

The docker_service resource i am trying to use is something like:

```
docker_service 'default' do
  install_method 'package'
  package_name 'docker-engine'
  version <version>
  storage_driver 'overlay'
  action [:create, :start]
end
```

### Expected Result:
Test Kitchen should run without errors

### Actual Result:

> * docker_service[default] action create
> 
>            ================================================================================
>            Error executing action `create` on resource 'docker_service[default]'
>            ================================================================================
> 
>            NoMethodError
>            -------------
>            undefined method `property_is_set?' for #<#<Class:0x00000000034f1e58>:0x0000000004eb8508>
> 
>            Cookbook Trace:
>            ---------------
>            /tmp/kitchen/cache/cookbooks/docker/libraries/docker_service.rb:47:in `validate_install_method'
>            /tmp/kitchen/cache/cookbooks/docker/libraries/docker_service.rb:95:in `block in <class:DockerService>'
